### ISSUE TITLE
ValueError when trying to write intervals to file

### ISSUE THREAD

**Issue by sandve** [bionumpy/bionumpy#11]
The following code:
intervals = merge_intervals(sort_intervals(bnp.open(in_fn).read()))
bnp.open(outFn, "w").write(intervals)

Using "hg38.ensGene.gtf.gz" from "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/genes/" as input,

throws this exception:
ValueError: negative dimensions are not allowed

Why does it not work, and is it possible to provide a better error message to describe this problem?

**Comment by knutdrand** [comment]
What is the outfilename here? 
In order for sort_intervals to work as expected, the intervals needs to be grouped by chromosome first, but I dont think that's where the error message comes from

**Comment by sandve** [comment]
With the following lines:
def sort_and_merge_bed_file(in_fn, outFn):
    grouped_intervals = groupby(bnp.open(in_fn).read(),"chromosome")
    intervals = merge_intervals(sort_intervals(grouped_intervals))
    bnp.open(outFn, "w").write(intervals)

sort_and_merge_bed_file("hg38.gtf", "hg38_sorted_merged.gtf")

I now get this error:
...
 File "/Users/geirksa/PycharmProjects/bionumpy/gc_multiple_chr.py", line 54, in sort_and_merge_bed_file
    grouped_intervals = groupby(bnp.open(in_fn).read(),"chromosome")
  File "/Users/geirksa/PycharmProjects/bionumpy/bionumpy/npdataclassstream.py", line 110, in new_func
    return func(*args, **kwargs)
  File "/Users/geirksa/PycharmProjects/bionumpy/bionumpy/groupby.py", line 54, in groupby
    changes = get_changes(keys)
  File "/Users/geirksa/PycharmProjects/bionumpy/bionumpy/groupby.py", line 11, in get_changes
    return get_ragged_changes(array)
  File "/Users/geirksa/PycharmProjects/bionumpy/bionumpy/groupby.py", line 24, in get_ragged_changes
    eq = next_row_values!=ragged_array[:-1]
  File "/Users/geirksa/PycharmProjects/bionumpy/venv/lib/python3.9/site-packages/numpy/lib/mixins.py", line 21, in func
    return ufunc(self, other)
  File "/Users/geirksa/PycharmProjects/bionumpy/bionumpy/sequences.py", line 117, in __array_ufunc__
    assert isinstance(self._data, EncodedArray), self._data
AssertionError: [ 99 104 114 ... 104 114  89]

**Comment by knutdrand** [comment]
Ahh yes, after merging, it is no longer a valid gtf file. Should be written as a bedfile I think.

**Comment by sandve** [comment]
#Now trying this code:
def sort_and_merge_bed_file(in_fn, out_fn):
    grouped_intervals = groupby(bnp.open(in_fn).read(),"chromosome")
    intervals = merge_intervals(sort_intervals(grouped_intervals))
    bnp.open(out_fn, "w").write(intervals)

sort_and_merge_bed_file("mini.gtf", "hg38_sorted_merged.bed")

With this file mini.gtf:
chr1	ensGene	transcript	11869	14409	.	+	.	gene_id "ENSG00000223972"; transcript_id "ENST00000456328";  gene_name "ENSG00000223972";
chr1	ensGene	exon	13221	14409	.	+	.	gene_id "ENSG00000223972"; transcript_id "ENST00000456328"; exon_number "3"; exon_id "ENST00000456328.3"; gene_name "ENSG00000223972";
chr1	ensGene	transcript	12010	13670	.	+	.	gene_id "ENSG00000223972"; transcript_id "ENST00000450305";  gene_name "ENSG00000223972";

Giving this exception (note one cause and one follow-up exception..):
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/dataclasses.py", line 1033, in fields
    fields = getattr(class_or_instance, _FIELDS)
AttributeError: 'GroupedStream' object has no attribute '__dataclass_fields__'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/geirksa/PycharmProjects/bionumpy/gc_multiple_chr.py", line 58, in <module>
    sort_and_merge_bed_file("mini.gtf", "hg38_sorted_merged.bed")
  File "/Users/geirksa/PycharmProjects/bionumpy/gc_multiple_chr.py", line 56, in sort_and_merge_bed_file
    bnp.open(out_fn, "w").write(intervals)
  File "/Users/geirksa/PycharmProjects/bionumpy/bionumpy/parser.py", line 186, in write
    bytes_array = self._buffer_type.from_data(data)
  File "/Users/geirksa/PycharmProjects/bionumpy/bionumpy/delimited_buffers.py", line 169, in from_data
    for field in dataclasses.fields(data)]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/dataclasses.py", line 1035, in fields
    raise TypeError('must be called with a dataclass type or instance')
TypeError: must be called with a dataclass type or instance

**Comment by knutdrand** [comment]
Have you pulled after this commit: https://github.com/bionumpy/bionumpy/commit/d1bada5132ccabdc479ee0801236999017825c31

**Comment by knutdrand** [comment]
Everything should work now, but needs a pull from npstructures/dev also

**Comment by sandve** [comment]
Ah. I was at master. Switched to dev, and then the mini file worked!

I got a next error though:
/Users/geirksa/PycharmProjects/bionumpy/bionumpy/strops.py:84: RuntimeWarning: divide by zero encountered in log10
  lengths = np.log10(number).astype(int)+1

This didn't tell me the offending line of the data file (maybe catch and re-raise exceptions in the parser so as to include the line number with the exception?!). I gues it is this large file that contains a few weird values;) 
(it is not my file but a standard UCSC file, though, so good to handle without exception..)

**Comment by sandve** [comment]
And when thinking about it, you probably don't do it line by line, so another strategy might be needed if we are to give more details about the error  - perhaps not realistic to achieve actually..

**Comment by sandve** [comment]
I now pulled the latest version, and then also the "mini.gtf" file above gives this error:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/geirksa/PycharmProjects/bionumpy/gc_multiple_chr.py", line 59, in <module>
    sort_and_merge_bed_file("medi.gtf", "hg38_sorted_merged.bed")
  File "/Users/geirksa/PycharmProjects/bionumpy/gc_multiple_chr.py", line 54, in sort_and_merge_bed_file
    grouped_intervals = groupby(bnp.open(in_fn).read(),"chromosome")
  File "/Users/geirksa/PycharmProjects/bionumpy/bionumpy/files.py", line 29, in read
    return self._reader.read().get_data()
  File "/Users/geirksa/PycharmProjects/bionumpy/bionumpy/delimited_buffers.py", line 373, in get_data
    col = self.get_text(col_number, fixed_length=False)
  File "/Users/geirksa/PycharmProjects/bionumpy/bionumpy/delimited_buffers.py", line 119, in get_text
    return self._move_intervals_to_ragged_array(starts, ends)
  File "/Users/geirksa/PycharmProjects/bionumpy/bionumpy/file_buffers.py", line 112, in _move_intervals_to_ragged_array
    return EncodedRaggedArray(self._data[indices], shape)
  File "/Users/geirksa/PycharmProjects/bionumpy/bionumpy/encoded_array.py", line 13, in __init__
    assert isinstance(self._data, EncodedArray)
AssertionError

**Comment by knutdrand** [comment]
It works at my computer now. I think we can give line-nr error messages for badly formatted files, if we can catch it in time. But for unexpected bugs it will probably only give chunk-nr
