### ISSUE TITLE
Write floats to file

### ISSUE THREAD

**Issue by pavlovicmilena** [bionumpy/bionumpy#30]
* bionumpy version: latest from dev branch (commit: 8610eebaad55a3d1702f5db0373bac912ee73a8c)
* Python version: 3.8
* Operating System: MacOS

### Description

I tried writing an array of floats to a file, but it broke.

### What I Did

```
from bionumpy.bnpdataclass import bnpdataclass
from bionumpy.io import delimited_buffers
import bionumpy as bnp

@bnpdataclass
class TestDC:
    p_gen: float
    
a = TestDC(p_gen=[0.1, 0.4])
buff_type = delimited_buffers.get_bufferclass_for_datatype(TestDC, delimiter="\t", has_header=True)

with bnp.open("tmp.tsv", buffer_type=buff_type, mode='w') as file:
    file.write(a)

```

Error:
```
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "bionumpy/io/parser.py", line 229, in write
    bytes_array = self._buffer_type.from_data(data)
  File "bionumpy/io/delimited_buffers.py", line 248, in from_data
    return dump_csv(data_dict, cls.DELIMITER)
  File "bionumpy/io/dump_csv.py", line 38, in dump_csv
    columns = [get_func_for_datatype(key)(value) for key, value in data_dict]
  File "bionumpy/io/dump_csv.py", line 38, in <listcomp>
    columns = [get_func_for_datatype(key)(value) for key, value in data_dict]
  File "bionumpy/io/strops.py", line 207, in float_to_strings
    return split(EncodedArray(b[1:-1]), sep=",")
TypeError: __init__() missing 1 required positional argument: 'encoding'
```

**Comment by knutdrand** [comment]
Fixed now using vanilla python
