### ISSUE TITLE
support for the fna file extension

### ISSUE THREAD

**Issue by nick-youngblut** [bionumpy/bionumpy#77]
* bionumpy version: 1.0.11
* Python version: 3.9.18
* Operating System: osx 

### Description

```
Traceback (most recent call last):
  File "/Users/nickyoungblut/dev/tmp/demux/./reads-find.py", line 44, in main
    query = bnp.open(args.query_fasta).read()
  File "/Users/nickyoungblut/mambaforge/envs/sc/lib/python3.9/site-packages/bionumpy/io/files.py", line 179, in bnp_open
    return _get_buffered_file(filename, suffix, mode, is_gzip=is_gzip, buffer_type=buffer_type, lazy=lazy)
  File "/Users/nickyoungblut/mambaforge/envs/sc/lib/python3.9/site-packages/bionumpy/io/files.py", line 56, in _get_buffered_file
    buffer_type = _get_buffer_type(suffix)
  File "/Users/nickyoungblut/mambaforge/envs/sc/lib/python3.9/site-packages/bionumpy/io/files.py", line 77, in _get_buffer_type
    raise RuntimeError(f"File format {suffix} does not have a default buffer type. "
RuntimeError: File format .fna does not have a default buffer type. Specify buffer_type argument using get_bufferclass_for_datatype function oruse one of '.vcf', '.bed', '.bdg', '.narrowPeak', '.fasta', '.fa', '.fastq', '.fq', '.gfa', '.gff', '.gtf', '.gff3', '.sam', '.bam', '.sizes', '.wig', '.pairs', '.pa5'
```

### What I Did

```python
import bionumpy as bnp
bnp.open("sequence.fna").read()
```

### Why support `*.fna`?

`*.fna` is commonly used to distinguish between nucleotide (`*.fna`) and amino acid (`*.faa`) fasta files. It appears that you do not support `*.faa` either.

### Misc

It would be helpful to have an example in the docs on specifying the `buffer_type` argument using `get_bufferclass_for_datatype` function.

There's also a typo in the error message: `oruse`

**Comment by knutdrand** [comment]
Thanks for the input! Missing .fna .faa was an oversight. I've also added better error messages for unsupported file suffixes so that it's easier to find the right buffer_type (which in this case was bnp.MultiLineFastaBuffer)

**Comment by nick-youngblut** [comment]
Thanks!

**Comment by nick-youngblut** [comment]
Thanks!
